project_id = "szrjikvwdygyyxfztfvn"

[functions.customer-sign-quotation]
verify_jwt = false

[functions.quotation-pdf]
verify_jwt = false

[functions.generate-quotation-pdf]
verify_jwt = false

[functions.generate-payment-docs]
verify_jwt = false

[functions.portone-create-link]
verify_jwt = false

[functions.portone-webhook]
verify_jwt = false
